---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-13.10

suites:
  - name: default
    run_list:
      - recipe[chruby-build::default]
    attributes:

  - name: rubies_data_bags
    run_list:
      - recipe[chruby-build::rubies]
    attributes:

  - name: rubies_attributes
    run_list:
      - recipe[chruby-build::rubies]
    attributes:
      chruby_build:
        rubies_libs:
          - libyaml-dev
          - libssl-dev
          - libreadline-dev
          - zlib1g-dev
        google_perftools:
          enable: false
        libyaml:
          enable: false
        rubies:
          - id: "ruby-2.0.0-p247"
            url: "http://cache.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p247.tar.gz"
            gems:
              - bundler
              - pry
