---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-16.04-chef-12
    driver:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 12.21.3

suites:
  - name: default
    run_list:
      - recipe[chruby-build::default]
    attributes:

  - name: rubies_data_bags
    run_list:
      - recipe[chruby-build::rubies]
    attributes:

  - name: rubies_attributes
    run_list:
      - recipe[chruby-build::rubies]
    attributes:
      chruby_build:
        rubies_libs:
          - libyaml-dev
          - libssl-dev
          - libreadline-dev
          - zlib1g-dev
        google_perftools:
          enable: false
        libyaml:
          enable: false
        rubies:
          - id: "ruby-2.4.1"
            url: "https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.1.tar.gz"
            gems:
              - bundler
              - pry
