name             'chruby-build'
maintainer       'Vincent Durand'
maintainer_email 'vincent.durand@madwork.org'
license          'MIT'
description      'Installs/Configures chruby'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
supports         'ubuntu', '>= 12.04'
depends          'apt', '>= 2.3'
depends          'ark', '>= 0.6'
